# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: question.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'question.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0equestion.proto\x12\x04main\"-\n\x0fQuestionRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"[\n\x08NewsItem\x12\x10\n\x08interest\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12\x0b\n\x03url\x18\x04 \x01(\t\x12\x10\n\x08\x64istance\x18\x05 \x01(\x02\"2\n\x10QuestionResponse\x12\x1e\n\x06\x61nswer\x18\x01 \x03(\x0b\x32\x0e.main.NewsItem2G\n\x0fQuestionService\x12\x34\n\x03\x41sk\x12\x15.main.QuestionRequest\x1a\x16.main.QuestionResponseB\tZ\x07./;mainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'question_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./;main'
  _globals['_QUESTIONREQUEST']._serialized_start=24
  _globals['_QUESTIONREQUEST']._serialized_end=69
  _globals['_NEWSITEM']._serialized_start=71
  _globals['_NEWSITEM']._serialized_end=162
  _globals['_QUESTIONRESPONSE']._serialized_start=164
  _globals['_QUESTIONRESPONSE']._serialized_end=214
  _globals['_QUESTIONSERVICE']._serialized_start=216
  _globals['_QUESTIONSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
